<a href="https://colab.research.google.com/github/LuisChore/algorithmic_trading/blob/main/finance_analysis/investment_risk/02_covariance_correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. Covariance

$ Cov\;Matrix = \begin{bmatrix}
\sigma_1 ^{2} & \sigma_{1,2} ^{2} & \cdots  &\sigma_{1,I} ^{2}  \\
\sigma_{2,1} ^{2}&\sigma_2 ^{2}  & \cdots & \sigma_{2,I} ^{2} \\
\vdots  & \vdots & \ddots  &  \\
 \sigma_{I,1} ^{2}&\sigma_{I,2} ^{2}  &  & \sigma_{I} ^{2} \\
\end{bmatrix} $

* Representation of the way two and more variables relate each other.
* The main diagonal are the variance of each one of the variables.

In [ ]:
!pip install --upgrade pandas
!pip install --upgrade pandas-datareader

In [2]:
import numpy as np
import pandas as pd
import pandas_datareader.data as wb
import matplotlib.pyplot as plt

In [3]:
'''
returns the historical price data of a company, including the percentage daily 
change, daily log return
'''
def log_return(ticket,data_source,start_year):
  info = wb.DataReader(ticket,data_source,start = start_year)
  info['log_return'] = np.log((info['Adj Close'] / info['Adj Close'].shift(1)))
  return info

### Annual Covariance Matrix

In [4]:
'''
Calculates the ANNUAL COVARIANCE MATRIX of different tickets using the 
logarithmic rate of returns
@TODO: check that all the companies have the same amount of returns              
'''
def annual_cov_matrix(tickets,start_year):
  data = pd.DataFrame()
  for ticket in tickets:
    data[ticket] = log_return(ticket,'yahoo',start_year)['log_return']
  cov_matrix = data.cov() * 250 #annualizing 
  return cov_matrix

In [5]:
tickets = ['PG','MSFT','F','GE']
start_year = 2005
annual_cov_matrix(tickets,start_year)

            PG      MSFT         F        GE
PG    0.033146  0.022573  0.021879  0.022867
MSFT  0.022573  0.073801  0.043280  0.036373
F     0.021879  0.043280  0.178742  0.065655
GE    0.022867  0.036373  0.065655  0.111551

## 02. Correlation

Correlation between **returns of the companies**.

It reflects the dependence between prices at different times and focuses on the returns of your portfolio. It is not necessary annualize the result, it shows only the relation between the two variables

In [6]:
'''
@TODO: check that all the companies have the same amount of returns      
'''
def corr_matrix(tickets,start_year):
  data = pd.DataFrame()
  for ticket in tickets:
    data[ticket] = log_return(ticket,'yahoo',start_year)['log_return']
  corr_matrix = data.corr() #not necessary annualizing
  return corr_matrix

In [7]:
tickets = ['PG','MSFT','F','GE']
start_year = 2005
corr_matrix(tickets,start_year)

            PG      MSFT         F        GE
PG    1.000000  0.456405  0.284250  0.376056
MSFT  0.456405  1.000000  0.376820  0.400876
F     0.284250  0.376820  1.000000  0.464965
GE    0.376056  0.400876  0.464965  1.000000

### Example with different number of returns

The correlation function ignore null values, it is ok if one of the companies does not have old data

In [8]:
tickets = ['MSFT','UBER']
corr_matrix(tickets,'2005')

          MSFT      UBER
MSFT  1.000000  0.427686
UBER  0.427686  1.000000

In [9]:
tickets = ['MSFT','UBER']
corr_matrix(tickets,'2019-05-10')

          MSFT      UBER
MSFT  1.000000  0.427684
UBER  0.427684  1.000000